import Footer from './components/Footer/footer'
import Navigation from './components/Navigation/navigation'
import './globals.css'
import { Inter, Montserrat } from 'next/font/google'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'Rekadigi',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body 
        className={montserrat.className}
      >
        {/* <Navigation /> */}

        {children}

        <Footer />
      </body>
    </html>
  )
}
